// Random life-event card bank — high-quality, arc-tagged scenes.
// Each card is a regular GameCard so it plugs into the existing engine and
// the event director can prefer them via tags.

import type { GameCard } from "../types";

export const RANDOM_EVENT_CARDS: GameCard[] = [
  // ─── RANDOM CRUSH (10) ─────────────────────────────────────────────────────
  {
    id: "rc_bus_stand",
    title: "বৃষ্টির বাস স্ট্যান্ড",
    location: "রাস্তা",
    phase: "Evening",
    category: "crush",
    speaker: "সেলিম",
    text: "বৃষ্টির বাস স্ট্যান্ডে এক মেয়ে জিগ্যেস করলো, 'ভাই, মিরপুরের বাস কোনটা?' সেলিম তোমার দিকে তাকালো: 'ভাই, voice ta soft ছিলো।'",
    tags: ["crush", "random"],
    weight: 14,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "শুধু রাস্তা বলে দিতে বল", kind: "smart", effects: { selfRespect: 4, iq: 3, romanticFever: -3 }, resultText: "সেলিম route বলে দিলো। Normal interaction survived।" },
      { label: "সাহায্য কর, কিন্তু extra smile না", kind: "do", effects: { selfRespect: 2, mood: 2, romanticFever: 2 }, resultText: "Route বললো। ৩ second extra smile। Manageable।" },
      { label: "বল 'destiny ভাবিস না'", kind: "avoid", effects: { iq: 4, selfRespect: 5, romanticFever: -5 }, resultText: "সেলিম মাথা নাড়লো। পরে বললো 'right ছিলি'।" },
      { label: "তোর মন বলছে যা—কথা চালিয়ে যা", kind: "later", effects: { romanticFever: 12, emotionalDelusion: 8, selfRespect: -3 }, resultText: "সেলিম 'First Love Again' মুডে চলে গেলো।", flagUpdate: { firstLoveCount: 1, randomCrushes: 1 } },
    ],
  },
  {
    id: "rc_bazar_smile",
    title: "বাজারের হাসি",
    location: "রাস্তা",
    phase: "Noon",
    category: "crush",
    speaker: "সেলিম",
    text: "বাজারে সবজির দোকানে এক মেয়ে দাম জিগ্যেস করতে গিয়ে হাসলো। সেলিম: 'ভাই, smile ta normal ছিলো না।'",
    tags: ["crush", "random"],
    weight: 10,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "Smile মানে commitment না বল", kind: "smart", effects: { iq: 4, selfRespect: 4, romanticFever: -4 }, resultText: "সেলিম মেনে নিলো। বাজার থেকে শুধু সবজি নিয়ে ফিরলো।" },
      { label: "নিজের কাজ কর, ভাবিস না", kind: "avoid", effects: { selfRespect: 3, mood: 2 }, resultText: "সেলিম ফোকাস ফিরালো।" },
      { label: "ঠিক আছে, একটু কথা বল", kind: "do", effects: { romanticFever: 6, mood: 3 }, resultText: "একটু কথা হলো। সাধারণ। সেলিম তবু রাতে ভাববে।" },
      { label: "নাম জিগ্যেস কর", kind: "later", effects: { romanticFever: 14, emotionalDelusion: 10, selfRespect: -5 }, resultText: "সেলিম nervous হলো। মেয়েটা চলে গেলো। সেলিম রাত জাগবে।", flagUpdate: { randomCrushes: 1 } },
    ],
  },
  {
    id: "rc_wrong_number",
    title: "ভুল নাম্বার মেসেজ",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "crush",
    speaker: "সেলিম",
    text: "Unknown number থেকে message: 'Sorry, ভুল নাম্বার।' সেলিম পড়লো ৫ বার। 'ভাই, tone টা polite ছিলো।'",
    tags: ["crush", "random"],
    weight: 9,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "Reply দিস না, ঘুমাতে যা", kind: "smart", effects: { selfRespect: 5, iq: 4, romanticFever: -5 }, resultText: "সেলিম phone রেখে ঘুমালো। Win।" },
      { label: "শুধু 'no problem' লিখ", kind: "do", effects: { selfRespect: 2, romanticFever: 1 }, resultText: "Polite reply। Conversation শেষ। ভালো।" },
      { label: "'কে আপনি?' জিগ্যেস কর", kind: "avoid", effects: { romanticFever: 8, emotionalDelusion: 6, selfRespect: -3 }, resultText: "চ্যাট চলে গেলো ৪০ মিনিট। সেলিম ভাবলো 'eibar different'।", flagUpdate: { randomCrushes: 1 } },
      { label: "বল 'destiny এই নাম্বারে আনলো'", kind: "later", effects: { romanticFever: 15, emotionalDelusion: 12, selfRespect: -6, iq: -2 }, resultText: "সেলিম পুরো future plan করে ফেললো। সকালে number block।", flagUpdate: { firstLoveCount: 1, randomCrushes: 1 } },
    ],
  },
  {
    id: "rc_old_classmate_inbox",
    title: "পুরোনো ক্লাসমেট ইনবক্স",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "crush",
    speaker: "সেলিম",
    text: "পুরোনো school classmate Facebook-এ বললো 'Selim! কেমন আছিস?' সেলিম: 'ভাই, ১২ বছর পর mention—মানে কিছু একটা।'",
    tags: ["crush", "random", "online"],
    weight: 8,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "ভালো আছি বলে চুপ", kind: "smart", effects: { selfRespect: 4, iq: 3 }, resultText: "Polite reply। সেলিম সরে এলো।" },
      { label: "Catch up কর, normal", kind: "do", effects: { mood: 3, romanticFever: 3 }, resultText: "Normal চ্যাট। Memory lane।" },
      { label: "'কেন হঠাৎ?' জিগ্যেস কর", kind: "avoid", effects: { iq: 4, selfRespect: 3 }, resultText: "মেয়েটা বললো group reunion plan। Ah।" },
      { label: "অনেক বছর পর—এটা signal", kind: "later", effects: { romanticFever: 14, emotionalDelusion: 12, selfRespect: -4 }, resultText: "সেলিম যা ভাবলো তা না। Group reunion ছিলো। সেলিম একা imagine করেছে।", flagUpdate: { firstLoveCount: 1, randomCrushes: 1 } },
    ],
  },
  {
    id: "rc_story_react",
    title: "Story-তে heart react",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "crush",
    speaker: "সেলিম",
    text: "সেলিমের boring story-তে এক মেয়ে heart দিলো। সেলিম: 'একজন full screen-time-er মধ্যে আমাকেই বেছে নিয়েছে।'",
    tags: ["crush", "random", "online"],
    weight: 9,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "Like = love না, বল", kind: "smart", effects: { iq: 5, selfRespect: 4, romanticFever: -5 }, resultText: "সেলিম মেনে নিলো। Phone নামালো।" },
      { label: "DM দিস না, কাজে মন দে", kind: "avoid", effects: { selfRespect: 5, careerProgress: 3 }, resultText: "সেলিম laptop খুললো।" },
      { label: "একটা thanks DM দে", kind: "do", effects: { romanticFever: 6, mood: 2 }, resultText: "মেয়েটা reply দিলো না। সেলিম একটু sad।" },
      { label: "'destiny algorithmer hat e'—DM দে", kind: "later", effects: { romanticFever: 14, emotionalDelusion: 10, selfRespect: -4 }, resultText: "Long DM। Seen। সেলিম নাকি ভেঙে যাচ্ছে।", flagUpdate: { randomCrushes: 1 } },
    ],
  },
  {
    id: "rc_tea_stall_eye",
    title: "চা স্টলে চোখাচুখি",
    location: "চা স্টল",
    phase: "Evening",
    category: "crush",
    speaker: "সেলিম",
    text: "চা স্টলে এক মেয়ে চা নিতে এসে accidentally চোখে চোখ পড়লো ০.৫ second। সেলিম: 'ভাই, eye contact দীর্ঘ ছিলো।'",
    tags: ["crush", "random"],
    weight: 9,
    visual: { sceneKey: "chaStallFriendTalk", overlay: "comedy" },
    choices: [
      { label: "চা খা, ভাবিস না", kind: "smart", effects: { selfRespect: 4, iq: 3, romanticFever: -3 }, resultText: "সেলিম চা শেষ করলো। Move on।" },
      { label: "Polite হাসি দে, ব্যস", kind: "do", effects: { selfRespect: 2, mood: 1 }, resultText: "ছোট hi। মেয়েটা চলে গেলো।" },
      { label: "Friend Mama-কে জিগ্যেস কর", kind: "avoid", effects: { friendTrust: 4, iq: 3 }, resultText: "Cha Mama বললেন: 'বাবা, চোখ পড়লেই love না।'" },
      { label: "Number চাইতে যা", kind: "later", effects: { romanticFever: 12, selfRespect: -6, mood: -3 }, resultText: "মেয়েটা বললো 'sorry ভাই'। Cha Mama মুখ ঘুরালেন।", flagUpdate: { randomCrushes: 1, heartbreakCount: 1 } },
    ],
  },
  {
    id: "rc_tuition_sister",
    title: "টিউশনির বড় বোন",
    location: "মেস বাড়ি",
    phase: "Evening",
    category: "crush",
    speaker: "সেলিম",
    text: "যে student-কে সেলিম পড়ায়, তার বড় বোন এসে চা দিয়ে বললো 'ভাই, কষ্ট করছেন।' সেলিম: 'ভাই, eta normal না।'",
    tags: ["crush", "random"],
    weight: 8,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "Thanks বলে পড়াতে যা", kind: "smart", effects: { selfRespect: 5, iq: 3, careerProgress: 3 }, resultText: "সেলিম professional থাকলো। Tuition continue।" },
      { label: "Politely কথা বল, কাজ ছাড়িস না", kind: "do", effects: { selfRespect: 3, romanticFever: 3 }, resultText: "Decent ব্যবহার। Tuition বাঁচলো।" },
      { label: "Number চাইতে যাবি?", kind: "avoid", effects: { romanticFever: 10, selfRespect: -8, careerProgress: -5 }, resultText: "ঘরের মা শুনে ফেললো। Tuition গেলো।", flagUpdate: { randomCrushes: 1 } },
      { label: "ছাত্রকে বল 'আপু কি করেন?'", kind: "later", effects: { romanticFever: 12, selfRespect: -10, careerProgress: -8, mood: -5 }, resultText: "ছাত্র বাসায় বললো। Tuition বন্ধ। সেলিম নিজেকে গালি দিলো।", flagUpdate: { randomCrushes: 1, heartbreakCount: 1 } },
    ],
  },
  {
    id: "rc_clinic_waiting",
    title: "ক্লিনিকে অপেক্ষা",
    location: "অফিস",
    phase: "Noon",
    category: "crush",
    speaker: "সেলিম",
    text: "ক্লিনিকের waiting room-এ এক মেয়ে phone-এ কথা বলতে বলতে সেলিমের পাশে বসলো। সেলিম: 'ভাই, perfume টা—।'",
    tags: ["crush", "random"],
    weight: 7,
    visual: { sceneKey: "careerStruggle", overlay: "comedy" },
    choices: [
      { label: "নিজের serial wait কর", kind: "smart", effects: { selfRespect: 5, health: 3 }, resultText: "সেলিম doctor-এর কাছে গেলো। Done।" },
      { label: "চুপ থাক", kind: "avoid", effects: { selfRespect: 3 }, resultText: "Silence। Both সরে এলো।" },
      { label: "Hi বলে ছোট কথা", kind: "do", effects: { romanticFever: 5, mood: 2 }, resultText: "Polite ছোট কথা। মেয়েটা চলে গেলো।" },
      { label: "'একই doctor?' জিগ্যেস কর", kind: "later", effects: { romanticFever: 12, emotionalDelusion: 8, selfRespect: -5 }, resultText: "মেয়েটা hesitate করলো। Awkward।", flagUpdate: { randomCrushes: 1 } },
    ],
  },
  {
    id: "rc_recharge_shop",
    title: "রিচার্জ দোকানের মেয়ে",
    location: "রাস্তা",
    phase: "Evening",
    category: "crush",
    speaker: "সেলিম",
    text: "Mobile recharge দোকানে নতুন মেয়ে। 'কত টাকা ভাই?' জিগ্যেস করতে গিয়ে সেলিম stuck। 'ভাই, আমি ভুলে গেছি কত recharge করতে এসেছিলাম।'",
    tags: ["crush", "random"],
    weight: 7,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "৫০ টাকার recharge করে চলে যা", kind: "smart", effects: { selfRespect: 4, iq: 3, money: -50 }, resultText: "Normal transaction। Done।" },
      { label: "Polite থাক, কথা বাড়াইস না", kind: "do", effects: { selfRespect: 2, money: -50 }, resultText: "Decent।" },
      { label: "প্রতি দিন এসে recharge কর", kind: "avoid", effects: { romanticFever: 10, money: -150, selfRespect: -3 }, resultText: "এক সপ্তাহে ৩ বার এসেছে। দোকানদার মুচকি হাসছে।", flagUpdate: { randomCrushes: 1 } },
      { label: "নাম জিগ্যেস কর", kind: "later", effects: { romanticFever: 12, money: -50, selfRespect: -6, mood: -3 }, resultText: "মেয়েটা বললো 'ভাই, আমার boyfriend আছে।'", flagUpdate: { heartbreakCount: 1, randomCrushes: 1 } },
    ],
  },
  {
    id: "rc_wedding_cousin",
    title: "বিয়েতে cousin-এর friend",
    location: "মেস বাড়ি",
    phase: "Evening",
    category: "crush",
    speaker: "সেলিম",
    text: "Cousin-এর বিয়েতে এক মেয়ে stage সাজানো দেখছে। Cousin বললো 'ও আমার friend।' সেলিম: 'ভাই, friend মানে trust আছে।'",
    tags: ["crush", "random"],
    weight: 7,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "comedy" },
    choices: [
      { label: "Hi বলে ছবি তুলতে যা", kind: "smart", effects: { selfRespect: 4, mood: 3 }, resultText: "Normal interaction। Wedding enjoy করলো।" },
      { label: "Cousin-এর সাথে হাঁট", kind: "avoid", effects: { selfRespect: 3, friendTrust: 3 }, resultText: "Distance maintain।" },
      { label: "Cousin-কে বল 'ভাই, intro দে'", kind: "do", effects: { romanticFever: 6, mood: 2 }, resultText: "Cousin চোখ ঘুরালো। Intro দিলো। ৩ minute কথা।" },
      { label: "Number চাইতে যা", kind: "later", effects: { romanticFever: 14, selfRespect: -6, mood: -5 }, resultText: "মেয়েটা cousin-কে বললো। পুরো family জানলো।", flagUpdate: { randomCrushes: 1, heartbreakCount: 1 } },
    ],
  },

  // ─── PINKY COMEBACK / MIXED SIGNALS (5) ────────────────────────────────────
  {
    id: "pc_you_changed",
    title: "Pinky: 'You changed'",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "love",
    speaker: "পিঙ্কি",
    text: "Long silence-এর পর Pinky message: 'You changed। আগের সেই Selim কই?' সেলিম তোমার দিকে phone ঘুরালো।",
    tags: ["pinky", "comeback"],
    weight: 18,
    condition: (s) => s.stats.selfRespect > 50 || s.stats.pinkyHope < 60,
    visual: { sceneKey: "rainyHeartbreak", overlay: "romantic" },
    choices: [
      { label: "Reply দিস না, boundary রাখ", kind: "smart", effects: { selfRespect: 8, pinkyHope: -5, friendTrust: 5 }, resultText: "সেলিম phone নামালো। Win।", flagUpdate: { pinkyBoundaryWins: 1 } },
      { label: "'কেমন আছো?' শুধু বল", kind: "do", effects: { selfRespect: 3, pinkyHope: 4 }, resultText: "Short polite reply। Pinky double-text করলো।" },
      { label: "'I miss you' লিখ", kind: "avoid", effects: { selfRespect: -8, pinkyHope: 12, emotionalDelusion: 8 }, resultText: "Pinky 'aww' দিলো। সেলিম রাত জাগবে।", flagUpdate: { firstLoveCount: 1 } },
      { label: "'recharge লাগবে?' জিগ্যেস কর", kind: "later", effects: { selfRespect: -12, money: -200, pinkyHappiness: 8, pinkyHope: 6 }, resultText: "Pinky বললো 'tumi এত care কর'। সেলিম গলে গেলো।", flagUpdate: { pinkyRechargeCount: 1, girlInvestment: 200 } },
    ],
  },
  {
    id: "pc_proud_of_you",
    title: "Pinky: 'Proud of you'",
    location: "মেস বাড়ি",
    phase: "Evening",
    category: "love",
    speaker: "পিঙ্কি",
    text: "Career-এ একটু progress হতেই Pinky text: 'Heard you got new project। Proud of you।' সেলিম তোমাকে call দিলো।",
    tags: ["pinky", "comeback"],
    weight: 14,
    condition: (s) => s.stats.careerProgress >= 40,
    visual: { sceneKey: "rainyHeartbreak", overlay: "romantic" },
    choices: [
      { label: "Thanks বলে কাজে মন দে", kind: "smart", effects: { selfRespect: 8, careerProgress: 4, pinkyHope: -3 }, resultText: "Selim laptop-এ ফিরলো। Strong।", flagUpdate: { pinkyBoundaryWins: 1 } },
      { label: "Short reply, no over-explain", kind: "do", effects: { selfRespect: 4 }, resultText: "Brief। Pinky double-text করতে পারলো না।" },
      { label: "'তোমার জন্যই এই motivation' লিখ", kind: "avoid", effects: { selfRespect: -10, pinkyHope: 14, emotionalDelusion: 10, careerProgress: -3 }, resultText: "Selim career credit Pinky-কে দিলো। Distraction শুরু।", flagUpdate: { firstLoveCount: 1 } },
      { label: "Coffee plan suggest কর", kind: "later", effects: { selfRespect: -8, money: -300, pinkyHappiness: 10, careerProgress: -5 }, resultText: "Coffee meeting। সেলিম পরে বললো 'eibar different ছিল'।", flagUpdate: { girlInvestment: 300 } },
    ],
  },
  {
    id: "pc_maybe_one_day",
    title: "Pinky: 'Maybe one day'",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "love",
    speaker: "পিঙ্কি",
    text: "Direct question-এর উত্তরে Pinky: 'Maybe one day, when timing right হবে।' সেলিম এটা পড়লো ১২ বার।",
    tags: ["pinky", "ambiguous"],
    weight: 14,
    visual: { sceneKey: "rainyHeartbreak", overlay: "romantic" },
    choices: [
      { label: "'Maybe' = no, বল সেলিমকে", kind: "smart", effects: { selfRespect: 10, emotionalDelusion: -8, pinkyHope: -10 }, resultText: "সেলিম মাথা নামালো। কিন্তু পরিষ্কার হলো।", flagUpdate: { pinkyBoundaryWins: 1 } },
      { label: "Wait কর কিন্তু life চালা", kind: "do", effects: { selfRespect: 3, careerProgress: 3 }, resultText: "Balanced। সেলিম কাজে ফিরলো।" },
      { label: "'ami wait করবো' লিখ", kind: "avoid", effects: { selfRespect: -10, emotionalDelusion: 14, pinkyHope: 10 }, resultText: "Pinky 'aww' দিলো। সেলিম ১৫ দিন পরও wait করছে।", flagUpdate: { firstLoveCount: 1 } },
      { label: "'কত দিন wait করবো?' জিগ্যেস কর", kind: "later", effects: { selfRespect: -5, mood: -8, pinkyHope: -3 }, resultText: "Pinky 'pressure দিও না' বললো। সেলিম sorry লিখলো।" },
    ],
  },
  {
    id: "pc_post_with_guy",
    title: "Pinky-এর post-এ অন্য ছেলে",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "love",
    speaker: "সেলিম",
    text: "Pinky-এর Instagram post-এ unknown ছেলের সাথে। সেলিম zoom করে দেখছে। 'ভাই, এটা কে?'",
    tags: ["pinky", "jealousy"],
    weight: 12,
    visual: { sceneKey: "rainyHeartbreak", overlay: "danger" },
    choices: [
      { label: "Phone রেখে দে, ঘুমা", kind: "smart", effects: { selfRespect: 10, mood: 3, addiction: -3 }, resultText: "সেলিম phone off করলো। বাঁচলো।", flagUpdate: { pinkyBoundaryWins: 1 } },
      { label: "Story stalk বন্ধ কর", kind: "avoid", effects: { selfRespect: 6, iq: 3 }, resultText: "Self control। Sleep ভালো হলো।" },
      { label: "Pinky-কে DM দিয়ে জিগ্যেস কর", kind: "do", effects: { selfRespect: -8, pinkyHope: -5, mood: -10 }, resultText: "Pinky 'tumi possessive' বললো। সেলিম sorry।", flagUpdate: { pinkySeenCount: 1 } },
      { label: "ছেলেটার profile খুঁজ", kind: "later", effects: { selfRespect: -12, mood: -15, addiction: 8, iq: -3 }, resultText: "৩ ঘণ্টা detective। কেউ না, cousin ছিলো। সেলিম কাঁদলো।", flagUpdate: { heartbreakCount: 1 } },
    ],
  },
  {
    id: "pc_emotional_call_before_interview",
    title: "Interview-এর আগে Pinky call",
    location: "মেস বাড়ি",
    phase: "Morning",
    category: "love",
    speaker: "পিঙ্কি",
    text: "Interview ১৫ minute আগে Pinky call: 'আমি ভেঙে পড়েছি, তুমি ছাড়া কেউ নাই।' সেলিম প্যান্ট পরা অবস্থায় freeze।",
    tags: ["pinky", "career_vs_love"],
    weight: 14,
    condition: (s) => s.day >= 5,
    visual: { sceneKey: "rainyHeartbreak", overlay: "danger" },
    choices: [
      { label: "Interview-এ যা, পরে call দিস", kind: "smart", effects: { selfRespect: 12, careerProgress: 10, pinkyHope: -5 }, resultText: "সেলিম interview দিলো। Pinky একটু sulk। But Selim won।", flagUpdate: { pinkyBoundaryWins: 1, playerAdviceFollowed: 1 } },
      { label: "২ minute কথা বলে দৌড়া", kind: "do", effects: { selfRespect: 3, careerProgress: 3 }, resultText: "Late হলেও interview দিলো। Manageable।" },
      { label: "Interview cancel কর, ও কাঁদছে", kind: "avoid", effects: { selfRespect: -15, careerProgress: -15, pinkyHope: 10, emotionalDelusion: 10 }, resultText: "Interview missed। Pinky ১০ minute পর 'thanks bondhu' লিখলো।", flagUpdate: { emotionalOverrides: 1, playerAdviceIgnored: 1 } },
      { label: "Phone off করে interview-এ যা", kind: "later", effects: { selfRespect: 14, careerProgress: 12, pinkyHope: -10, mood: -5 }, resultText: "সেলিম phone off। Interview ভালো হলো। Pinky পরে রাগ করলো, but Selim দাঁড়িয়েছে।", flagUpdate: { pinkyBoundaryWins: 1 } },
    ],
  },

  // ─── CAREER VS LOVE (4) ─────────────────────────────────────────────────────
  {
    id: "cv_freelance_deadline",
    title: "Freelance deadline বনাম emotional চ্যাট",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "career",
    speaker: "সেলিম",
    text: "৩ ঘণ্টা পর deadline। Pinky chat: 'কথা বলবা না? তুমি অন্য রকম হয়ে গেছো।' সেলিম: 'ভাই, কী করি?'",
    tags: ["career", "career_vs_love"],
    weight: 14,
    condition: (s) => s.day >= 4,
    visual: { sceneKey: "careerStruggle", overlay: "career" },
    choices: [
      { label: "Phone নামিয়ে কাজ শেষ কর", kind: "smart", effects: { careerProgress: 12, selfRespect: 10, pinkyHope: -5 }, resultText: "Project submitted। Client খুশি। Selim proud।", flagUpdate: { pinkyBoundaryWins: 1 } },
      { label: "১০ minute reply, তারপর কাজ", kind: "do", effects: { careerProgress: 5, selfRespect: 3 }, resultText: "Balanced। Deadline শেষ ৫ minute আগে।" },
      { label: "চ্যাটে ডুব দে, deadline পরে", kind: "avoid", effects: { careerProgress: -15, money: -500, selfRespect: -10, mood: -8 }, resultText: "Project late। Client refund চাইলো। সেলিম কাঁদলো।", flagUpdate: { emotionalOverrides: 1 } },
      { label: "Pinky-কে call দে", kind: "later", effects: { careerProgress: -10, selfRespect: -8, mood: -10 }, resultText: "২ ঘণ্টা call। Project incomplete। Pinky ১১টায় 'good night' বললো।", flagUpdate: { emotionalOverrides: 1 } },
    ],
  },
  {
    id: "cv_salary_day_gift",
    title: "Salary day-এ Pinky-এর gift hint",
    location: "অফিস",
    phase: "Evening",
    category: "money",
    speaker: "সেলিম",
    text: "Salary পেলো। Pinky story: 'ও যেই perfume চেয়েছিলাম, কেউ গিফট দিলে কী যে খুশি হতাম 🥺।' সেলিম তোমাকে ছবি পাঠালো।",
    tags: ["money", "pinky", "career_vs_love"],
    weight: 12,
    condition: (s) => s.day >= 6,
    visual: { sceneKey: "pinkyEffectWalk", overlay: "danger" },
    choices: [
      { label: "Rent আগে দে, gift না", kind: "smart", effects: { selfRespect: 12, money: 0, pinkyHope: -5 }, resultText: "Rent দিলো। Pinky 'ohh' দিলো। Selim দাঁড়িয়েছে।", flagUpdate: { rentPaid: 1, pinkyBoundaryWins: 1 } },
      { label: "Save কর, পরে ভাব", kind: "do", effects: { selfRespect: 6, money: 100 }, resultText: "Selim wait করলো। ৩ দিন পর Pinky ভুলে গেছে।" },
      { label: "Cheap dupe কিন bring", kind: "avoid", effects: { selfRespect: -3, money: -300, pinkyHappiness: 5 }, resultText: "Pinky polite thanks। Story-তে post করলো না।", flagUpdate: { girlInvestment: 300 } },
      { label: "Original কিন bring", kind: "later", effects: { selfRespect: -10, money: -1500, pinkyHappiness: 15, romanticFever: 10 }, resultText: "Pinky story-তে 'best gift ever 🥹'। Tag: cousin। Rent: pending।", flagUpdate: { girlInvestment: 1500 } },
    ],
  },
  {
    id: "cv_morning_class_late_chat",
    title: "Late-night chat-এর পর সকালের class",
    location: "অফিস",
    phase: "Morning",
    category: "career",
    speaker: "সেলিম",
    text: "রাত ৩টা পর্যন্ত Pinky-এর সাথে chat। ৭টায় important class। Alarm বাজছে। সেলিম: 'ভাই, ১০ minute আরও।'",
    tags: ["career", "career_vs_love"],
    weight: 11,
    visual: { sceneKey: "careerStruggle", overlay: "career" },
    choices: [
      { label: "উঠে যা, class miss করিস না", kind: "smart", effects: { careerProgress: 10, selfRespect: 8, energy: -5 }, resultText: "Class attended। Tired but proud।" },
      { label: "১০ minute পর ওঠ", kind: "do", effects: { careerProgress: 4, energy: -3 }, resultText: "Late পৌঁছালো। Teacher ভ্রু কুঁচকালো।" },
      { label: "Class skip কর, ঘুমা", kind: "avoid", effects: { careerProgress: -10, energy: 5, mood: -3 }, resultText: "ঘুমিয়ে রইলো। Important note miss।", flagUpdate: { emotionalOverrides: 1 } },
      { label: "Pinky-কে morning text দে", kind: "later", effects: { careerProgress: -5, selfRespect: -3, romanticFever: 5 }, resultText: "Pinky ১১টায় উঠে reply দিলো। Class শেষ।" },
    ],
  },
  {
    id: "cv_career_win_pinky_back",
    title: "Career win-এর পর Pinky comeback",
    location: "মেস বাড়ি",
    phase: "Evening",
    category: "career",
    speaker: "সেলিম",
    text: "Project complete, ভালো review পেলো। সাথে সাথে Pinky text: 'Tumi এত successful, ভয় লাগে।' সেলিম তোমাকে ছবি পাঠালো।",
    tags: ["career", "pinky", "comeback"],
    weight: 12,
    condition: (s) => s.stats.careerProgress >= 50,
    visual: { sceneKey: "boguraBossRooftop", overlay: "career" },
    choices: [
      { label: "Boundary রাখ, focus career", kind: "smart", effects: { selfRespect: 14, careerProgress: 6, pinkyHope: -5 }, resultText: "Selim politely 'thanks' বলে কাজে ফিরলো।", flagUpdate: { pinkyBoundaryWins: 1 } },
      { label: "Thanks বলে light কথা", kind: "do", effects: { selfRespect: 4, mood: 3 }, resultText: "Brief reply। Selim balanced।" },
      { label: "'তুমি always inspired করছো' লিখ", kind: "avoid", effects: { selfRespect: -8, emotionalDelusion: 10, pinkyHope: 12, careerProgress: -3 }, resultText: "Pinky-কে credit দিলো। নিজের win দাবি করতে পারলো না।", flagUpdate: { firstLoveCount: 1 } },
      { label: "Date suggest কর", kind: "later", effects: { selfRespect: -10, money: -500, careerProgress: -5, pinkyHappiness: 8 }, resultText: "Date হলো। Pinky 'still figuring out' বললো। সেলিম confused।", flagUpdate: { girlInvestment: 500 } },
    ],
  },

  // ─── FRIENDSHIP / BEST FRIEND (3) ───────────────────────────────────────────
  {
    id: "fr_check_after_heartbreak",
    title: "Heartbreak-এর পর তুই খোঁজ নিলি",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "social",
    speaker: "সেলিম",
    text: "Pinky-এর last seen-এর পর সেলিম দু'দিন silent। তুমি call দিলে। সেলিম: 'ভাই, আমি ঠিক আছি... actually ঠিক নাই।'",
    tags: ["friendship", "bestfriend"],
    weight: 12,
    condition: (s) => s.flags.heartbreakCount >= 1,
    visual: { sceneKey: "chaStallFriendTalk", overlay: "friendship" },
    choices: [
      { label: "শুধু শোন, advice দিস না", kind: "smart", effects: { friendTrust: 14, mood: 8, selfRespect: 5 }, resultText: "সেলিম কাঁদলো, তারপর হাসলো। 'তুই আছিস' বললো।", flagUpdate: { bestFriendMoments: 1 } },
      { label: "চা স্টলে নিয়ে যা", kind: "do", effects: { friendTrust: 10, mood: 6, money: -50 }, resultText: "Cha Mama-র দোকানে দু'জন। সেলিম একটু light।", flagUpdate: { bestFriendMoments: 1 } },
      { label: "'বললাম তো, ভুলে যা'", kind: "avoid", effects: { friendTrust: -8, mood: -5, selfRespect: -3 }, resultText: "সেলিম মুখ ঘুরালো। 'তুই বুঝবি না।' Silence।", flagUpdate: { silentMoments: 1 } },
      { label: "Pinky-কে call দিতে বল", kind: "later", effects: { friendTrust: -12, selfRespect: -8, pinkyHope: 5 }, resultText: "সেলিম phone-এ ঝাঁপ দিলো। তুই face palm করলি।", flagUpdate: { emotionalOverrides: 1 } },
    ],
  },
  {
    id: "fr_rafiq_brutal_truth",
    title: "Rafiq-এর brutal সত্য",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "social",
    speaker: "রাফিক",
    text: "Rafiq সরাসরি বললো: 'মামা, Pinky তোকে recharge ATM ভাবে। মাফ করিস, কিন্তু এটাই সত্য।' সেলিম তোমার দিকে তাকালো।",
    tags: ["friendship"],
    weight: 10,
    condition: (s) => s.flags.pinkyRechargeCount >= 2,
    visual: { sceneKey: "chaStallFriendTalk", overlay: "friendship" },
    choices: [
      { label: "Rafiq ঠিক বলেছে, সেলিম", kind: "smart", effects: { friendTrust: 8, selfRespect: 10, emotionalDelusion: -10 }, resultText: "সেলিম মাথা নাড়লো। 'বুঝতেছি ভাই।'", flagUpdate: { pinkyBoundaryWins: 1 } },
      { label: "Brutal but শোন", kind: "do", effects: { friendTrust: 5, selfRespect: 6 }, resultText: "সেলিম চুপ। ভাবছে।" },
      { label: "Rafiq-কে stop কর, ব্যথা দিচ্ছে", kind: "avoid", effects: { friendTrust: -5, selfRespect: -3, emotionalDelusion: 5 }, resultText: "সেলিম সরে গেলো। Rafiq চুপ।", flagUpdate: { defensiveMoments: 1 } },
      { label: "'তুই বুঝবি না Rafiq' বল", kind: "later", effects: { friendTrust: -12, selfRespect: -10, emotionalDelusion: 12 }, resultText: "Rafiq উঠে গেলো। সেলিম একা।", flagUpdate: { emotionalOverrides: 1, defensiveMoments: 1 } },
    ],
  },
  {
    id: "fr_will_you_leave_me",
    title: "সেলিম: 'তুইও কি চলে যাবি?'",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "social",
    speaker: "সেলিম",
    text: "রাত ১টায় সেলিম message: 'ভাই, সবাই চলে যায়। তুইও কি একদিন চলে যাবি?' সেলিম typing... typing... চুপ।",
    tags: ["friendship", "bestfriend"],
    weight: 10,
    condition: (s) => s.flags.heartbreakCount >= 1 || s.stats.loneliness > 60,
    visual: { sceneKey: "rooftopSilhouette", overlay: "friendship" },
    choices: [
      { label: "'আমি আছি, ঘুমা' লিখ", kind: "smart", effects: { friendTrust: 12, mood: 8, selfRespect: 4 }, resultText: "সেলিম 'thanks ভাই' লিখে ঘুমালো।", flagUpdate: { bestFriendMoments: 1 } },
      { label: "Voice call দে", kind: "do", effects: { friendTrust: 14, mood: 10 }, resultText: "৪০ minute কথা। সেলিম last-এ হাসলো।", flagUpdate: { bestFriendMoments: 1 } },
      { label: "'এত drama করিস না'", kind: "avoid", effects: { friendTrust: -10, mood: -10, selfRespect: -5 }, resultText: "সেলিম seen করে চুপ। Damage।", flagUpdate: { silentMoments: 1 } },
      { label: "Reply দিস না, সকালে দেখব", kind: "later", effects: { friendTrust: -6, mood: -5 }, resultText: "সকালে সেলিম 'sorry, drama করেছি' লিখলো। কিন্তু trust dent।" },
    ],
  },

  // ─── TOUBA RELAPSE COMEDY (3) ───────────────────────────────────────────────
  {
    id: "re_touba_whatsapp_notification",
    title: "Touba চলছে — Pinky-র notification",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "love",
    speaker: "সেলিম",
    text: "Touba চলছে Day 5। Phone উল্টো রাখা। হঠাৎ notification sound। সেলিম জানে দেখা উচিত না। কিন্তু... হাত নিজেই চলে গেলো।",
    tags: ["pinky", "touba", "comeback"],
    weight: 12,
    condition: (s) => s.flags.promiseModeTurnsLeft >= 1,
    visual: { sceneKey: "rainyHeartbreak", overlay: "comedy" },
    choices: [
      { label: "'Phone উল্টো থাক। Touba টিকুক।'", kind: "smart", effects: { selfRespect: 14, emotionalDelusion: -10, pinkyHope: -5 }, resultText: "সেলিম phone দেখলো না। সকালে দেখলো: notification ছিলো Grameenphone-এর। এত কষ্ট করলাম।", flagUpdate: { pinkyBoundaryWins: 1, playerAdviceFollowed: 1 } },
      { label: "'শুধু দেখি — reply না করলেই তো Touba'", kind: "do", effects: { selfRespect: -3, emotionalDelusion: 8, pinkyHope: 4 }, resultText: "Pinky-র story। নতুন DP। সেলিম ৩০ minute গেলো।" },
      { label: "'Touba-তে notification দেখা নেই তো'", kind: "avoid", effects: { selfRespect: -8, emotionalDelusion: 12, pinkyHope: 8 }, resultText: "Pinky: 'কেমন আছো।' Touba officially dead।", flagUpdate: { brokenPromiseCount: 1, rechargePromisesBroken: 1, promiseModeTurnsLeft: 0 } },
      { label: "রাফিককে ডাকি — সাক্ষী রাখি", kind: "later", effects: { friendTrust: 8, selfRespect: 8, emotionalDelusion: -5 }, resultText: "রাফিক এলো। দু'জন মিলে দেখলো: জিপি notification। রাফিক বললো 'দেখলি, Touba জিতলো।'", flagUpdate: { bestFriendMoments: 1, playerAdviceFollowed: 1 } },
    ],
  },
  {
    id: "re_touba_broken_excuse_masterclass",
    title: "Touba ভাঙার Masterclass",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "love",
    speaker: "সেলিম",
    text: "Touba ভাঙলো। Day 2-এ। এবার সেলিম excuses নিয়ে এসেছে। রাফিক clipboard নিয়ে বসলো। 'বল, এবার কী excuse?'",
    tags: ["touba", "comedy", "pinky"],
    weight: 8,
    condition: (s) => s.flags.brokenPromiseCount >= 2 && s.flags.rechargePromisesBroken >= 1,
    visual: { sceneKey: "chaStallFriendTalk", overlay: "comedy" },
    choices: [
      { label: "'কোনো excuse নেই। আমি fail করেছি।'", kind: "smart", effects: { selfRespect: 15, emotionalDelusion: -12, friendTrust: 8 }, resultText: "রাফিক clipboard নামালো। 'এই কথাটাই শুনতে চেয়েছিলাম। আবার শুরু করি?'", flagUpdate: { bestFriendMoments: 1, pinkyBoundaryWins: 1 } },
      { label: "'Force majeure ছিলো — Pinky online ছিলো'", kind: "do", effects: { selfRespect: -5, emotionalDelusion: 8, friendTrust: -3 }, resultText: "রাফিক লিখলো 'Excuse #7: Pinky online। Classic।'", flagUpdate: { brokenPromiseCount: 1 } },
      { label: "'এবার different। Official restart।'", kind: "avoid", effects: { selfRespect: 5, emotionalDelusion: -3 }, resultText: "রাফিক: 'তুই প্রতিবার বলিস।' কিন্তু হাত বাড়ালো। 'চল আবার।'", flagUpdate: { promisesMade: 1, promiseModeTurnsLeft: 2 } },
      { label: "'Touba timer-এর concept ভুল ছিলো আসলে'", kind: "later", effects: { selfRespect: -10, emotionalDelusion: 12, iq: -3 }, resultText: "৩০ minute philosophical debate। Touba postponed indefinitely।", flagUpdate: { brokenPromiseCount: 1, rechargePromisesBroken: 1 } },
    ],
  },
  {
    id: "re_touba_new_record",
    title: "Personal Best: ৬ দিন!",
    location: "মেস বাড়ি",
    phase: "Evening",
    category: "love",
    speaker: "রাফিক",
    text: "রাফিক চিৎকার করলো: 'ভাই! ৬ দিন! তোর personal best! Pinky-কে recharge দিসনি, text করিসনি, last seen চেকও করিসনি।' মেসের অন্যরাও হাততালি দিলো।",
    tags: ["touba", "comedy", "bestfriend"],
    weight: 7,
    condition: (s) => s.flags.pinkyBoundaryWins >= 3 && s.flags.brokenPromiseCount >= 1,
    visual: { sceneKey: "boguraBossRooftop", overlay: "career" },
    choices: [
      { label: "'Celebrate! Day 7 টিকবো।'", kind: "smart", effects: { selfRespect: 15, mood: 18, emotionalDelusion: -10, friendTrust: 8 }, resultText: "Day 7 complete। রাফিক biryani treat করলো। সেলিম জিতলো।", flagUpdate: { bestFriendMoments: 1, playerAdviceFollowed: 1 } },
      { label: "'এই সাফল্য Pinky-কে জানাই'", kind: "do", effects: { selfRespect: -12, emotionalDelusion: 12, pinkyHope: 5 }, resultText: "'Pinky, ৬ দিন তোমাকে miss করিনি।' Pinky: 'okay।' Day 7: failed।", flagUpdate: { brokenPromiseCount: 1, rechargePromisesBroken: 1 } },
      { label: "'আসলে চেক করেছি, শুধু text করিনি'", kind: "avoid", effects: { selfRespect: -3, iq: 2 }, resultText: "সেলিম confession করলো। রাফিক: 'তাহলে half credit।'" },
      { label: "এই momentum-এ আর কোনো কাজ করি", kind: "later", effects: { selfRespect: 10, careerProgress: 8, mood: 12 }, resultText: "Positive momentum! সেলিম CV update করলো। ঢাকা দেখছে।", flagUpdate: { workCount: 1 } },
    ],
  },

  // ─── FAMILY / BOGURA (3) ────────────────────────────────────────────────────
  {
    id: "fa_mother_call",
    title: "মা-র call from Bogura",
    location: "মেস বাড়ি",
    phase: "Evening",
    category: "family",
    speaker: "সেলিম",
    text: "মা call: 'বাবা, ঠিকমতো খাচ্ছিস? সকালে ফোনই ধরিস না।' সেলিম গলা পরিষ্কার করলো।",
    tags: ["family", "bogura"],
    weight: 11,
    visual: { sceneKey: "rooftopSunset", overlay: "friendship" },
    choices: [
      { label: "শোন, gently কথা বল", kind: "smart", effects: { mood: 10, selfRespect: 5, loneliness: -8 }, resultText: "মা একটু হাসলো। সেলিম-ও।", flagUpdate: { motherCallsAnswered: 1 } },
      { label: "টাকা পাঠাব বলে phone রাখ", kind: "do", effects: { mood: 5, selfRespect: 3 }, resultText: "Promise করলো। মা 'ঠিকাছে' বললো।", flagUpdate: { motherCallsAnswered: 1 } },
      { label: "ব্যস্ত বলে কেটে দে", kind: "avoid", effects: { mood: -8, selfRespect: -8, loneliness: 5 }, resultText: "মা silence-এ phone কাটলো। সেলিম guilty।" },
      { label: "Phone ধরিস না", kind: "later", effects: { mood: -12, selfRespect: -12, loneliness: 10 }, resultText: "মা ৩ বার call দিলো। সেলিম ছাদে গেলো একা।" },
    ],
  },
  {
    id: "fa_village_friend_message",
    title: "Village friend: 'ঢাকায় কেমন?'",
    location: "মেস বাড়ি",
    phase: "Night",
    category: "family",
    speaker: "সেলিম",
    text: "Bogura-র পুরোনো friend message: 'মামা, Dhaka-তে এখন কেমন? বিয়ে-শাদির খবর কিছু?' সেলিম ছাদে গেলো।",
    tags: ["family", "bogura"],
    weight: 8,
    visual: { sceneKey: "rooftopSilhouette", overlay: "friendship" },
    choices: [
      { label: "Honest answer দে", kind: "smart", effects: { friendTrust: 5, mood: 4, selfRespect: 5 }, resultText: "Friend বললো 'ভাই, তুই-ই পারবি'। সেলিম একটু শক্তি পেলো।" },
      { label: "Joke দিয়ে ঘুরিয়ে দে", kind: "do", effects: { mood: 3 }, resultText: "Banter। Light।" },
      { label: "'great চলছে, business booming'", kind: "avoid", effects: { selfRespect: -5, mood: -3, emotionalDelusion: 5 }, resultText: "Lie বললো। নিজে নিজেকে বিশ্বাস করতে পারলো না।" },
      { label: "Reply দিস না", kind: "later", effects: { loneliness: 8, mood: -5 }, resultText: "সেলিম phone নামিয়ে আকাশের দিকে তাকিয়ে রইলো।" },
    ],
  },
  {
    id: "fa_family_food_courier",
    title: "বাড়ির খাবার courier",
    location: "মেস বাড়ি",
    phase: "Noon",
    category: "family",
    speaker: "সেলিম",
    text: "Courier-এ মা-র পাঠানো ঘি, আচার, পিঠা। সেলিম box খুলে চুপ। 'ভাই, মা ভাবে আমি ভালো নাই।'",
    tags: ["family", "bogura"],
    weight: 7,
    visual: { sceneKey: "rooftopSunset", overlay: "friendship" },
    choices: [
      { label: "মা-কে call দিয়ে thanks বল", kind: "smart", effects: { mood: 12, loneliness: -10, selfRespect: 6 }, resultText: "মা কাঁদলো একটু। সেলিম-ও।", flagUpdate: { motherCallsAnswered: 1 } },
      { label: "Rafiq-এর সাথে share কর", kind: "do", effects: { friendTrust: 6, mood: 8 }, resultText: "দু'জন মিলে খেলো। মেস-এ হাসি।", flagUpdate: { bestFriendMoments: 1 } },
      { label: "Pinky-কে পাঠা", kind: "avoid", effects: { selfRespect: -8, money: -100, romanticFever: 5 }, resultText: "Pinky 'thanks' দিয়ে cousin-কে দিলো।", flagUpdate: { girlInvestment: 100 } },
      { label: "ফ্রিজে রেখে ভুলে যা", kind: "later", effects: { mood: -5, loneliness: 5 }, resultText: "৩ দিন পর পচা। সেলিম guilty।" },
    ],
  },
];
